-- BigQuery ML logistic regression model for synthetic risk scoring.
-- Trained on synthetic historical observations only.
-- Output is a demonstration risk score, not a validated clinical model.

CREATE OR REPLACE MODEL `${project_id}.${dataset_id}.risk_score_model`
OPTIONS(
  model_type = 'LOGISTIC_REG',
  input_label_cols = ['high_risk_label'],
  auto_class_weights = TRUE
) AS
SELECT
  bp_systolic,
  bp_diastolic,
  bmi,
  heart_rate,
  spo2,
  -- Synthetic label generated by the data generator for training purposes only.
  -- In this demo, "high_risk_label" is assigned by rule-based synthetic logic,
  -- not derived from real clinical outcomes.
  high_risk_label
FROM
  `${project_id}.${dataset_id}.training_observations_wide`;

-- Example scoring query, run per patient after each new observation batch:
-- SELECT
--   patient_id,
--   predicted_high_risk_label_probs[OFFSET(0)].prob AS ml_risk_score
-- FROM
--   ML.PREDICT(
--     MODEL `${project_id}.${dataset_id}.risk_score_model`,
--     (SELECT * FROM `${project_id}.${dataset_id}.latest_observations_wide`)
--   );
